# FactoryEye YOLO Training Configuration
path: data/processed
train: images/train
val: images/val
test: images/test

names:
  0: crazing
  1: inclusion
  2: patches
  3: pitted_surface
  4: rolled-in_scale
  5: scratches

# Default Hyperparameters
base_model: yolov8n.pt
epochs: 50
image_size: 640
batch_size: 32
learning_rate: 0.01
optimizer: auto
cache: true
